[[redirect]]
from = "/*"
to = "404.html"
status = 404

[[redirect]]
from = "https://js.popout.tk"
to = "https://ephf.github.io/popup/api/recent.js"
force = true
status = 301

[[redirect]]
from = "https://js.popout.tk/*"
to = "https://ephf.github.io/popup/api/:splat.js"
force = true
status = 301

[[redirect]]
from = "https://docs.popout.tk"
to = "https://ephf.github.io/popup/api/docs.html"
force = true
status = 301

[[headers]]
for = "https://js.popout.tk/*"
[headers.values]
Access-Control-Allow-Origin = "*"
