[[redirects]]
from = "/*"
to = "404.html"
status = 404

[[redirects]]
from = "https://js.popout.tk"
to = "https://ephf.github.io/popup/api/recent.js"
status = 301
force = true

[[redirects]]
from = "https://js.popout.tk/*"
to = "https://ephf.github.io/popup/api/:splat.js"
status = 301
force = true

[[redirects]]
from = "https://docs.popout.tk"
to = "https://ephf.github.io/popup/api/docs.html"
status = 301
force = true

[[headers]]
for = "https://js.popout.tk/*"
[headers.values]
Access-Control-Allow-Origin = "*"
