[[redirect]]
from = "/*"
to = "404.html"
status = 404

[[redirect]]
from = "https://js.popout.tk"
to = "api/recent.js"

[[redirect]]
from = "https://js.popout.tk/*"
to = "api/:splat.js"

[[redirect]]
from = "https://docs.popout.tk"
to = "api/docs.html"
