[[redirect]]
from = "/*"
to = "404.html"
status = 404

[[redirect]]
from = "js.popout.tk"
to = "api/recent.js"

[[redirect]]
from = "/js.popout.tk/*"
to = "api/:splat.js"

[[redirect]]
from = "docs.popout.tk"
to = "api/docs.html"

[[headers]]
for = "js.popout.tk/*"
[headers.values]
Access-Control-Allow-Origin = "*"
