[[redirect]]
from = "/*"
to = "404.html"
status = 404

[[redirect]]
from = "https://js.popout.tk"
to = "api/recent.js"
status = 200

[[redirect]]
from = "https://js.popout.tk/*"
to = "api/:splat.js"
status = 200

[[redirect]]
from = "https://docs.popout.tk"
to = "api/docs.html"
status = 200

[[headers]]
for = "https://js.popout.tk/*"
[headers.values]
Access-Control-Allow-Origin = "*"
